# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d67e520cdba6610c4948315a3346d88059ead739efce534c47db7fd336b7a2410b4ae456d06de246b79c0b7371f7bea635606d327d5bd0c5fd3009fa5d73c4d

test:
  secret_key_base: e9fe0cf75b41c2a0b1dac970e00c19152c10213e616ea77800f3ce6dd7fca467ea02cf132c0e0fb6411bcb5f5f5c30f985fd5b2d3a672abf4321b50cd2584f24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
